# serverless.yml

service: serverless-takeon-ui

plugins:
 - serverless-python-requirements
 - serverless-wsgi
custom:
 wsgi:
   app: application.application
   packRequirements: false

provider:
 name: aws
 runtime: python3.6
 stage: dev
 region: eu-west-2

functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'